[package]
name = "clone-closure"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
as-any = "0.3"
# wasmtime = "1.0"
# wasmtime-wasi = "1.0"

[[bin]]
name = "main2"